- name: install ntp package
  yum: pkg={{ ntp_pkg }} state=latest
- name: removing ntp.conf
  shell: rm -rf /etc/ntp.conf
- name: Copy ntp config file to /etc/ntp.conf
  copy: src=files/ntp.conf dest=/etc/ntp.conf owner=root group=root mode=644
  notify:
    - StartNTP
    - TestNTP
    - DisplayResult
